@extends('layouts.master')
@section('title')
    <h2>{{$page_title}}</h2>
@endsection
@section('content')
    @if(auth()->user()->type!='admin')
        @include('dashboard.'.auth()->user()->type)
    @endif
@endsection
